Repository crowbar/crowbar-ha, pull requests merged in 2018-10, with the labels that each got.

#312 [4.0] prevent systemd from owning Pacemaker-controlled services (bsc#980341)
  chef/cookbooks/pacemaker/recipes/default.rb
Labels: backport from SOC8

#335 pacemaker: Wait more for cluster to be online
  chef/cookbooks/crowbar-pacemaker/recipes/default.rb
  chef/cookbooks/pacemaker/recipes/default.rb
  crowbar_framework/app/models/pacemaker_service.rb
Labels: needs forward-port to SOC8, needs forward-port to SOC9, upgrade

#336 [5.0] pacemaker: Cleanup 4.0 specific attribute
  chef/data_bags/crowbar/migrate/pacemaker/204_remove_allow_larger_cluster.rb
  chef/data_bags/crowbar/template-pacemaker.json
Labels: upgrade

#333 upgrade: Add a healthcheck for pacemaker nodes state
  crowbar_framework/app/models/api/pacemaker.rb
Labels: forward-port from SOC7, upgrade

#338 pacemaker: Wait more for cluster to be online
  chef/cookbooks/crowbar-pacemaker/recipes/default.rb
  chef/cookbooks/pacemaker/recipes/default.rb
  crowbar_framework/app/models/pacemaker_service.rb
Labels: forward-port from SOC7, upgrade

#339 [5.0] pacemaker: Wait more for cluster to be online
  chef/cookbooks/crowbar-pacemaker/recipes/default.rb
  chef/cookbooks/pacemaker/recipes/default.rb
  crowbar_framework/app/models/pacemaker_service.rb
Labels: forward-port from SOC7, upgrade
