Repository crowbar/crowbar-ha, pull requests merged in 2018-04, with the labels that each got.

#308 [4.0] Fix a search for cluster founders.
  crowbar_framework/app/models/api/pacemaker.rb
Labels: upgrade

#306 [4.0] pacemaker: added support for op defaults
  chef/cookbooks/pacemaker/providers/primitive.rb
  chef/data_bags/crowbar/migrate/pacemaker/105_op_defaults.rb
  chef/data_bags/crowbar/template-pacemaker.json
  chef/data_bags/crowbar/template-pacemaker.schema
Labels: backport from SOC8

#305 Update corosync configuration correctly and in time when adding a new cluster node
  chef/cookbooks/corosync/recipes/config.rb
  chef/cookbooks/pacemaker/recipes/default.rb
  chef/cookbooks/pacemaker/spec/helpers/provider.rb
  crowbar_framework/app/models/pacemaker_service.rb
Labels: needs backport to SOC7

#307 [4.0] pacemaker: 2-node clusters should have two_node: 1 (bsc#1023981)
  chef/cookbooks/corosync/templates/default/corosync.conf.v2.erb
  chef/cookbooks/pacemaker/attributes/default.rb
  crowbar_framework/app/assets/javascripts/barclamps/pacemaker/application.js
Labels: backport from SOC8

#310 [4.0] Fix references to Node model.
  crowbar_framework/app/models/api/pacemaker.rb
Labels: upgrade
