Repository crowbar/crowbar-ha, pull requests merged in 2018-08, with the labels that each got.

#313 haproxy: increased SSL stick table to 100k
  chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb
Labels: needs backport to SOC7

#314 [4.0] haproxy: increased SSL stick table to 100k
  chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb
Labels: backport from SOC8

#315 Fix Pacemaker cluster online check
  chef/cookbooks/pacemaker/recipes/default.rb
Labels: needs backport to SOC7

#323 [4.0] drbd: Add switch to short circuit cluster size check
  chef/data_bags/crowbar/migrate/pacemaker/106_allow_larger_cluster.rb
  chef/data_bags/crowbar/template-pacemaker.json
  chef/data_bags/crowbar/template-pacemaker.schema
  crowbar_framework/app/models/pacemaker_service.rb
Labels: upgrade

#319 [4.0] crowbar-pacemaker: Cluster member SSH key improvements
  chef/cookbooks/crowbar-pacemaker/recipes/default.rb
Labels: needs forward-port to SOC8, needs forward-port to SOC9, upgrade
