Repository crowbar/crowbar-ha, pull requests merged in 2019-04, with the labels that each got.

#350 [4.0] improve galera HA setup (bsc#1122875)
  chef/cookbooks/haproxy/templates/default/haproxy.cfg.erb
Labels: backport from SOC9

#353 pacemaker: don't check cluster members on founder and extend timeout for SBD case (SCRD-8462)
  chef/cookbooks/crowbar-pacemaker/recipes/default.rb
  chef/cookbooks/pacemaker/recipes/default.rb
Labels: needs backport to SOC7, needs backport to SOC8

#354 [5.0] pacemaker: don't check cluster members on founder and extend timeout for SBD case (SCRD-8462)
  chef/cookbooks/crowbar-pacemaker/recipes/default.rb
  chef/cookbooks/pacemaker/recipes/default.rb
Labels: backport from SOC9

#355 [4.0] pacemaker: don't check cluster members on founder and extend timeout for SBD case (SCRD-8462)
  chef/cookbooks/crowbar-pacemaker/recipes/default.rb
  chef/cookbooks/pacemaker/recipes/default.rb
Labels: backport from SOC8
